import { Router } from "express";
const router = Router();
import { CreateApp, UpadetApp, DeleteApp, getAllApp, getApp, Search } from "../controllers/AppartmentController.js";
router.post("/", CreateApp);
router.get("/", getAllApp);
router.get("/:id", getApp);
router.get("/search", Search);
router.patch("/:id", UpadetApp);
router.delete("/:id", DeleteApp);
export default router;