export const actionTypes = {
    FETCH_APPS: "FETCH_APPS",
    CREATE_APP: "CREATE_APP",
    UPDATE_APP: "UPDATE_APP",
    DELETE_APP: "DELETE_APP",
	LOGIN_FAILURE:"LOGIN_FAILURE",
	LOGIN_SUCCESS:"LOGIN_SUCCESS",
	SIGNIN:"SIGNIN"

};
